### ISSUE TITLE
잘못된 자바 버전

### ISSUE THREAD

**Issue by bestheroz** [ceaser501/SpringSample#11]
https://github.com/ceaser501/SpringSample/blob/e8913c58fa3e39b5e3d04fd541b6f60f8128e2f8/src/main/java/edu/taesu/myspring/HomeController.java#L54

해당 라인은 자바7 이상일때 가능한데
pom.xml 에서는 자바6으로 되어 있어서 메이븐 빌드할때 에러 나요!

**Comment by ceaser501** [comment]
1.6에서 1.8로 올려서 push했습니다
