### ISSUE TITLE
ModelAndView 를 쓰는 이유가 있을까요?

### ISSUE THREAD

**Issue by bestheroz** [ceaser501/SpringSample#2]
https://github.com/ceaser501/SpringSample/blob/0b9d04f2d7e6a40c28b74e0e7296f21c7561b99d/src/main/java/edu/taesu/mySpring/TestController.java#L15

ModelAndView를 사용하면 소스량도 많아져서 안써도 되는데 사용하신 이유가 있을까요?
없으시면 ModelAndView는 사용하지 않아야 할거 같아요.

**Comment by ceaser501** [comment]
해당 파일 불필요하여 삭제 했습니다
굳이 ModelAndView를 사용해서 Model을 던져줄 이유도 없었구요
