### ISSUE TITLE
maven 에 설정된 ojdbc6.jar 는 왜 프로젝트에 포함되지 않은거죠?

### ISSUE THREAD

**Issue by bestheroz** [ceaser501/SpringSample#3]
https://github.com/ceaser501/SpringSample/blob/0b9d04f2d7e6a40c28b74e0e7296f21c7561b99d/pom.xml#L143

ojdbc6.jar 는 개발자마다 스스로 구축해야하는 건가요? 이유가 있을까요?

**Comment by ceaser501** [comment]
<dependency>
			<groupId>oracle.jdbc</groupId>
			<artifactId>jdbc</artifactId>
			<version>12.2.0.1</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/src/main/webapp/WEB-INF/lib/ojdbc7.jar</systemPath>
		</dependency>

pom.xml에서 이 구문내에서 ojdbc7.jar 파일을 프로젝트 path에서 가져오는데,
ojdbc7.jar 가 누락되었던 것 같습니다.
추가해서 commit 올려드리겠습니다.
