### ISSUE TITLE
log4j 와 logback을 섞어쓰는 이유가 있을까요?

### ISSUE THREAD

**Issue by bestheroz** [ceaser501/SpringSample#5]
https://github.com/ceaser501/SpringSample/blob/0b9d04f2d7e6a40c28b74e0e7296f21c7561b99d/src/main/resources/log4j.xml#L3

log4j는 log4j 에서...
logback은 slf4j에서.. 

처리하는 걸로 알고 있는데.. 서로다른 로거 두개를 섞어 쓰는데 이유가 있을까요?

**Comment by ceaser501** [comment]
logback을 새로 추가하면서, log4j 제거가 이루어 지지 않았습니다.
logback과 slf4j 만으로 로깅 처리를 하기 때문에, log4j는 제거했습니다.
