### ISSUE TITLE
없는 경로 인거 같아요.

### ISSUE THREAD

**Issue by bestheroz** [ceaser501/SpringSample#6]
https://github.com/ceaser501/SpringSample/blob/0b9d04f2d7e6a40c28b74e0e7296f21c7561b99d/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml#L16

**Comment by ceaser501** [comment]
정적 리소스 사용을 위한 경로 지정 구문입니다. webapp/resources/ 밑에 css, img, js 폴더를 만들고, 그 안에 필요한 리소스를 넣을 예정입니다. (임시로 logo.png를 넣었고, testTable.jsp에서 resources 를 불러오도록 해놨습니다)
<img src="<c:url value='/resources/img/logo.png' />" width="70px" height="60px" style="float:left;"/>
